### ISSUE TITLE
lookup.nextcloud.com is blocked by Hetzner

### ISSUE THREAD

**Issue by hidrarga** [nextcloud/lookup-server#130]
I'm not sure if this is the right place, but I noticed that the IPv4 of the lookup.nextcloud.com server was blocked by Hetzner, as you can see in this traceroute:
```
traceroute to lookup.nextcloud.com (176.9.217.60), 30 hops max, 60 byte packets
 1  _gateway (192.168.35.1)  1.071 ms  1.443 ms  1.835 ms
 2  bras-02str.bxl.be.edpnet.net (213.219.132.31)  20.538 ms  20.579 ms  20.629 ms
 3  router02.bruix.be.edpnet.net (212.71.11.53)  20.878 ms  20.860 ms  20.844 ms
 4  router01.adamtel.nl.edpnet.net (212.71.11.114)  21.437 ms router02.bruix.be.edpnet.net (212.71.11.126)  21.167 ms router01.adamtel.nl.edpnet.net (212.71.1.70)  22.390 ms
 5  decix2-gw.hetzner.com (80.81.193.164)  29.515 ms router01.adamtel.nl.edpnet.net (212.71.11.222)  23.589 ms router01.adamtel.nl.edpnet.net (212.71.11.177)  23.187 ms
 6  decix2-gw.hetzner.com (80.81.193.164)  36.180 ms  35.228 ms core24.fsn1.hetzner.com (213.239.224.89)  48.393 ms
 7  core23.fsn1.hetzner.com (213.239.224.73)  48.110 ms core24.fsn1.hetzner.com (213.239.224.89)  22.418 ms core23.fsn1.hetzner.com (213.239.224.73)  23.476 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  blocked.hetzner.com (88.198.255.174)  4284.932 ms !X  4292.992 ms !X *
```

However, the server is reachable in IPv6, so this is an issue only for Nextcloud servers that don't have IPv6 enabled.

Here is some details about IPv4 blocked by Hetzner, although you might need to contact them for more info: https://docs.hetzner.com/konsoleh/account-management/configuration/block/

**Comment by DecaTec** [comment]
Same here: Server has only IPv4 connectivity. 
`ping lookup.nextcloud.com` results in:

```
PING lookup.nextcloud.com (176.9.217.60) 56(84) bytes of data.
From blocked.hetzner.com (88.198.255.174) icmp_seq=1 Packet filtered
```

This also affects the cronjob. The table `oc_jobs` nearly contains 1000 entries similar to this one:

```
| 4284597 | OCA\LookupServerConnector\BackgroundJobs\RetryJob               | {"userId":"**removed**"}                                                                                                            |          0 |   1687935874 |           0 |                  0 | dc976b25e6412f5c2d4cfe6a489a1bcf |              1 |

```

**Comment by support-criegerde** [comment]
Same on our site.
Both, blocked.hetzner.com as well as high amount of oc_job-entries.

In addition we recognized an increasing cpu load.

**Comment by quenenni** [comment]
We have the exact same problem.

Because of it, the cron jobs are very very long (way too long, repeating the same sequence to reach lookup without success.

One month ticket no answer... sad!

Does anyone here found a solution (or an explanation)?

**Comment by support-criegerde** [comment]
If enabled, try to disable a php module:

`phpdismod sysvsem`

![image](https://github.com/nextcloud/lookup-server/assets/134060911/67995e52-c3b5-4830-8d3f-8d8f233df210)

Fixed it for now...
