### ISSUE TITLE
Add missing .htaccess file

### ISSUE THREAD

**Issue by oparoz** [nextcloud/lookup-server#21]
URLs such as `/users` won't work without the proper mod_rewrite rule.

Please add a .htaccess file containing:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

**Comment by MorrisJobke** [comment]
PRs are welcome

**Comment by oparoz** [comment]
Done https://github.com/nextcloud/lookup-server/pull/22
